/** Nội dung lỗi tập trung của web khách hàng. Thêm/sửa câu chữ tại đây. */
export const ERROR_TEXT: Record<string, string> = {
  ACCOUNT_NOT_FOUND: "Tài khoản không tồn tại. Vui lòng kiểm tra lại tên đăng nhập hoặc email.",
  PASSWORD_INCORRECT: "Mật khẩu không chính xác. Vui lòng nhập lại.",
  ACCOUNT_UNVERIFIED: "Tài khoản chưa được xác minh. Vui lòng kiểm tra email để xác minh.",
  ACCOUNT_LOCKED: "Tài khoản đã bị khóa. Vui lòng liên hệ quản trị viên.",
  ACCOUNT_UNAVAILABLE: "Tài khoản hiện không thể sử dụng. Vui lòng liên hệ quản trị viên.",
  LOGIN_REQUIRED: "Vui lòng đăng nhập để tiếp tục.",
  SESSION_EXPIRED: "Phiên đăng nhập đã hết. Vui lòng đăng nhập lại.",
  SESSION_INVALID: "Phiên đăng nhập không hợp lệ. Vui lòng đăng nhập lại.",
  PERMISSION_DENIED: "Bạn không có quyền thực hiện thao tác này.",
  INVALID_CREDENTIALS: "Thông tin đăng nhập không chính xác.",
  EMAIL_ALREADY_EXISTS: "Email này đã được sử dụng.",
  USERNAME_ALREADY_EXISTS: "Tên đăng nhập này đã được sử dụng.",
  INVALID_OTP: "Mã xác minh không chính xác.",
  OTP_EXPIRED: "Mã xác minh đã hết hiệu lực. Vui lòng yêu cầu mã mới.",
  PASSWORD_TOO_WEAK: "Mật khẩu chưa đủ mạnh. Vui lòng kiểm tra lại yêu cầu mật khẩu.",
  PASSWORD_CONFIRM_MISMATCH: "Mật khẩu xác nhận không khớp.",
  SOCIAL_LOGIN_FAILED: "Không thể đăng nhập bằng tài khoản liên kết. Vui lòng thử lại.",
  INSUFFICIENT_STOCK: "Một số sản phẩm không còn đủ số lượng. Vui lòng cập nhật giỏ hàng.",
  INVALID_DELIVERY_CODE: "Mã nhận hàng không đúng hoặc đã hết hiệu lực. Vui lòng kiểm tra lại.",
  ORDER_CONFLICT_RETRY: "Tồn kho vừa thay đổi. Vui lòng kiểm tra lại và thử đặt hàng lần nữa.",
  CHECKOUT_SESSION_REUSED: "Phiên đặt hàng đã cũ. Vui lòng quay lại giỏ hàng và thử lại.",
  TOO_MANY_PENDING_PAYMENTS: "Bạn đang có nhiều giao dịch chờ thanh toán. Vui lòng xử lý giao dịch cũ trước.",
  SHIPPER_UNAVAILABLE: "Shipper hiện không còn sẵn sàng. Vui lòng chọn shipper khác.",
  SHIPPER_CAPACITY_REACHED: "Shipper đã đạt số đơn tối đa. Vui lòng chọn shipper khác.",
  NETWORK_ERROR: "Không thể kết nối máy chủ. Hãy kiểm tra mạng hoặc địa chỉ API rồi thử lại.",
  BAD_REQUEST: "Thông tin gửi lên chưa hợp lệ. Vui lòng kiểm tra lại.",
  NOT_FOUND: "Không tìm thấy dữ liệu yêu cầu. Vui lòng tải lại trang.",
  CONFLICT: "Dữ liệu vừa thay đổi. Vui lòng tải lại và thử lại.",
  VALIDATION_ERROR: "Thông tin chưa hợp lệ. Vui lòng kiểm tra lại.",
  TOO_MANY_REQUESTS: "Bạn thao tác quá nhanh. Vui lòng chờ một lúc rồi thử lại.",
  SERVER_ERROR: "Hệ thống đang gặp sự cố. Vui lòng thử lại sau ít phút.",
  UNKNOWN_ERROR: "Không thể thực hiện thao tác. Vui lòng thử lại.",
};
